### ISSUE TITLE
gen.py fails to run

### ISSUE THREAD

**Issue by linuxwolf** [xsf/xeps#10]
The XEP rendering script, gen.py, cannot run with the new repo layout.

The errors are because the intermediate XML file is empty.  This appears to happen because gen.py (and its deps) assume the parent directory is the repository, rather than the current directory.

**Comment by winfried** [comment]
On 02-07-15 22:08, Matthew A. Miller wrote:

Hi,

> The XEP rendering script, gen.py, cannot run with the new repo layout.

Sorry I don't have time to dive into it right now, but this problem
should already be solved in: https://github.com/xsf/xsf-tools

Winfried

**Comment by bear** [comment]
@winfried is there a place where we can talk about xsf-tools -- i'm digging into gen.py and I see a lot of small changes that I am just itching to fix/update/change so I'm thinking that some of them have already been thought about.

**Comment by linuxwolf** [comment]
You're welcome to discuss "Editor" (not "editor" (-:  ) tooling in the editor@ MUC room, if you'd like.
