### ISSUE TITLE
TODO sections are barely visible in dark mode

### ISSUE THREAD

**Issue by sonnyp** [xsf/xeps#1013]
![Screenshot from 2020-11-24 10-25-12](https://user-images.githubusercontent.com/19673/100074904-94d90500-2e3f-11eb-9c54-fed21f287d11.png)

https://xmpp.org/extensions/xep-0385.html#sect-idm46114442020768

**Comment by mathieui** [comment]
@sonnyp Seems fine here, maybe that was a mixed state between old and new CSS?

![xmpp.org screenshot](https://pix.mathieui.net/o/kRJIe.png)
