### ISSUE TITLE
XEP-0449 - Stickers!

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1077]
Many chat apps have stickers such as WhatsApp, Signal, Telegram and Element (Matrix). Would be great to see this get made and released into XMPP

https://xmpp.org/extensions/xep-0449.html

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this repository, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

As you note, there is a XEP for stickers already.

XMPP is a protocol, and the XMPP Standards Foundation does not develop any software as an organization. XEPs tell developers how to implement something in a way that two implementations will be compatible with each other. If you're missing support for a feature in some XMPP software, the right place to file a feature request is with that software. It is the software developers who must implement it, not the XSF.
