### ISSUE TITLE
Distributed Rooms

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1079]
Is there a XEP for making rooms weather they are private or public to be stored on multiple servers?

Matrix does this and such a XEP will allow for rooms to be more censorship resistant and decentralised since the chat history will be stored on more than one server. And if one servers deletes the room or blocks it, it will still survive by running on the other servers.

This way if a room which has bob@a.com. charlie@b.com and alice@c.com have a room. servers a.com, b.com and c.com will have the history of the room chat saved on all three servers instead of one server.

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

Yes. There are a range of approaches to doing this, see:

- [XEP-0281: DMUC1: Distributed Multi-User Chat](https://xmpp.org/extensions/xep-0281.html)
- [XEP-0282: DMUC2: Distributed MUC](https://xmpp.org/extensions/xep-0282.html)
- [XEP-0289: Federated MUC for Constrained Environments](https://xmpp.org/extensions/xep-0289.html)

I am only aware of implementations of XEP-0289.
