### ISSUE TITLE
Metadata Encryption

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1080]
Is there a XEP for making metadata in the chat end-to-end encrypted?

Matrix also has this issue were its metadata is not encrypted. Meta that needs to be encrypted is timestamp, read receipts, from, emojis, etc.

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

"Metadata" is a broad term, and each piece of metadata that you may consider concealing would need specialized solutions. See [XEP-0420: Stanza Content Encryption](https://xmpp.org/extensions/xep-0420.html) which already covers a bunch of things.
