### ISSUE TITLE
Reading Indicators In Groups

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1081]
Is there a XEP for reading indicators for rooms chats with three or more people in them? Instead of using the checkmark indicator it will show who has read the message in the group?

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

See [XEP-0333](https://xmpp.org/extensions/xep-0333.html) which is implemented in multiple clients, including [Conversations](https://conversations.im/#confirmation).
