### ISSUE TITLE
Email Password Recovery

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1082]
Is there a XEP for email password recovery and adding an email address to your XMPP account?

This will be a good option to have to secure ones account if it gets hacked or if ones is bad with passwords.

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

Yes, an email address can be associated with an account using [XEP-0077](https://xmpp.org/extensions/xep-0077.html). It is up to servers to provide recovery facilities. Many do.
