### ISSUE TITLE
Self Destructing Messages

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1083]
Is there a XEP for having self destructing messages in XMPP? Other messaging apps such as Signal support. Having this in XMPP will be a great addition for privacy.

- Self destruct after being read setting
- Add timer on message (Self destruct after X)
- Set date and time when message self destructs

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

There was [a proposal for ephemeral messages](https://xmpp.org/extensions/inbox/ephemeral-messages.html), but it [was not approved](https://logs.xmpp.org/council/2018-06-06#2018-06-06-7dc5694501338bb5) as a XEP by the XSF council at the time.

The right way to move forwards with this is to initiate a discussion on the standards mailing list, and find some agreement about a better way to implement it that addresses the concerns raised by the council members. Then [submit a new proposal](https://xmpp.org/about/standards-process.html#submitting-a-xep).
