### ISSUE TITLE
Emoji Responses

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1084]
Is there a XEP to be able to add a emoji response to a message just like in Matrix?

Matrix is great except it is not its own protocol and is heavy on resources unlike XMPP. One feature XMPP is missing is emoji responses. By having such a feature, it will make XMPP for fun and can attract more users to using XMPP. I personally think this is one of the reasons why Matrix is growing fast over the past few years is this feature which many other chat apps do not have.

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

This feature is documented in [XEP-0444: Message Reactions](https://xmpp.org/extensions/xep-0444.html). It is implemented in some clients, including [Converse.js](https://conversejs.org/) and [Movim](https://movim.eu/).
