### ISSUE TITLE
Answer/Make Call & Invite To Call On Other Device

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1085]
Is there a XEP which can be integrated into clients which will allow someone to accept the call on their phone but instead of accepting the call to be on their phone, it will be answered on their computer?

This way you can have a device like a phone be like a remote and you can answer a call, make a call or invite someone to the call but the call itself will take place on another device such as your computer.

The use case for such a handy feature will be for gaming since overlays in-game can be messy since overlays do not work or all games and a better way to start a voice chat, accept a voice chat or invite someone to a voice chat will be to use another device such as your phone to do this but have the voice chat on your computer that you are gaming on.

This will be handy feature for gamers and can make XMPP a good voice chat platform for gamers.

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

When you receive a call over XMPP the call request goes to all your devices thanks to [XEP-0353](https://xmpp.org/extensions/xep-0353.html). All you need to do is use a client on your desktop that supports incoming calls using XEP-0353, such as [Beagle](https://beagle.im/) or [Dino](https://dino.im/), or a web client like [Movim](https://movim.eu/).
