### ISSUE TITLE
Depending on external resources

### ISSUE THREAD

**Issue by imaginator** [xsf/xeps#123]
While building the XEPs I notice that some of them depend on external resources that no longer exist.

from https://travis-ci.org/xsf/xmpp.org/builds/91354956#L1610:
```
********** Error report for XEP-0253 **********
********** Build Errors **********
Error while generating tex.xml for XEP-0253: warning: failed to load external entity "http://xsltsl.sourceforge.net/modules/date-time.xsl"compilation error: file http://xsltsl.sourceforge.net/modules/stdlib.xsl line 13 element importxsl:import : unable to load http://xsltsl.sourceforge.net/modules/date-time.xslwarning: failed to load external entity "http://xsltsl.sourceforge.net/modules/uri.xsl"
Error while converting xml to tex for XEP-0253: /tmp/XEPbuilder_w3O9Fg/xep-0253.tex.xml:1:0: no element found
```

**Comment by linuxwolf** [comment]
This looks like a problem in xsf-tools, not the xeps repo itself.

**Comment by SamWhited** [comment]
Closing this here since it is really a report for the website (I think?). Maybe @bear or someone can check if it's still a problem and open an issue there if it is. Thanks!

**Comment by bear** [comment]
@SamWhited it's no longer an issue for the website as we removed building the XEPs from the build process for generating the website
