### ISSUE TITLE
Create tool to execute the triaging workflow

### ISSUE THREAD

**Issue by horazont** [xsf/xeps#1237]
## Summary

The Editor has a more-or-less formalised triaging workflow described in [docs/TRIAGING.md](https://github.com/xsf/xeps/blob/master/docs/TRIAGING.md#flowchart). Doing these steps manually is tedious and error-prone.

## Work proposal

A tool should be created which, given two git commits (the PR head and the merge base between the PR head and the current main branch), triages the changes contained in that range and provides a machine-readable judgement and human-readable action items.

## Requirements

- MUST be accurate: In case of doubt, the tool should delegate to a human (by providing next steps on the output) instead of guessing.

- MUST provide machine-readable output: This is for future CI integration which may eventually post notices to GitHub or assign labels.

**Comment by moparisthebest** [comment]
I'll work on this one.

Looking at the TRIAGING document the only step I don't think can be sanely done with a script is:
> Are the changes for all XEPs purely editorial?

Unless someone has good ideas for that I guess I'll just skip it :/

**Comment by moparisthebest** [comment]
Am I supposed to run `tools/validate-xep0001-conformance.sh` on each new protoxep and/or each xep changed in this script also or does something else do that? (I think I should probably do it)

**Comment by guusdk** [comment]
I believe that you would be duplicating https://github.com/xsf/xeps/pull/1253 ?

**Comment by moparisthebest** [comment]
`<approver>Editor</approver>` is in 0419 and 0457, should that be a thing?
