### ISSUE TITLE
XEP-0390: Initiate Last Call

### ISSUE THREAD

**Issue by horazont** [xsf/xeps#1263]
Council just voted on issuing a Last Call for XEP-0390. Please do so:

FTR, the steps are (IIRC):

- Change to Proposed
- Set an expiration date in `<lastcall/>`
- Send an email

**Comment by horazont** [comment]
FWIW, announcement email can be generated by send-updates.py if you have a sufficiently diffed xeplist.xml

**Comment by iNPUTmice** [comment]
I've started the Last Call.
