### ISSUE TITLE
Make "XEP-0308: Last Message Correction" compatible with MAM

### ISSUE THREAD

**Issue by Nyco** [xsf/xeps#146]
As discussed during XMPP Summit 19, [XEP-0308: Last Message Correction](https://xmpp.org/extensions/xep-0308.html) should be compatible with [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html).

**Comment by lovetox** [comment]
pardon my ignorance, why should that not be compatible?

**Comment by Nyco** [comment]
Pardon my ignorance if that is already compatible...
It is about pagination corner cases: you request msg 1 to 10, and the correction is 11.

**Comment by tfar** [comment]
This might just be a client issue, not? Just fetch more messages than you want to display.

**Comment by SamWhited** [comment]
Closing since there's been no response for a while and no one's quite sure what the issue is.
