### ISSUE TITLE
Pubsub: error when modifying multiple affiliations

### ISSUE THREAD

**Issue by tylorr** [xsf/xeps#15]
When modifying multiple pubsub affiliations the [extension states](https://xmpp.org/extensions/xep-0060.html#owner-affiliations-multi):

> the service MUST return an IQ error (which SHOULD be <not-acceptable/>) with the invalid entries, where the affiliation returned is the original, un-altered affiliation

But the provided [example](https://xmpp.org/extensions/xep-0060.html#example-207) is not following this rule. It does not list which affiliation modifications are not acceptable.

**Comment by stpeter** [comment]
Good point. That's a spec bug and needs to be fixed.

**Comment by stpeter** [comment]
I will create a PR for this.

**Comment by stpeter** [comment]
See https://github.com/xsf/xeps/pull/305

**Comment by SamWhited** [comment]
Fixed in 1.13.4 by 16194d4
