### ISSUE TITLE
Pubsub: affiliation state change questions

### ISSUE THREAD

**Issue by tylorr** [xsf/xeps#16]
In the [affiliations section](https://xmpp.org/extensions/xep-0060.html#affiliations) it talks about affiliation state changes and for a change from publisher to member is shows `n/a`.  What does that mean exactly? Does that mean a publisher cannot be changed to a member? Do they have to be changed to none first then to a member?

**Comment by stpeter** [comment]
If an owner removes an entity from the publisher list, the entity's affiliation changes to none. Adding an entity to the member list would not change the entity's affiliation from publisher to member. Thus there's no direct way to change an affiliation from publisher to member.

**Comment by tylorr** [comment]
Thanks, I think I understand now. One more quick question, if a user has the publish-only affiliation and an owner adds the user to the member list, would that user now become a publisher (member+publish-only)?

**Comment by tylorr** [comment]
I'm still wondering about the publish-only affiliation. The reverse of my question is a little weird.

1. User joe is a member
2. Owner sets affiliation to publish-only triggering Joe to be added to the publisher list
3. Joe is now a publisher, not publish-only (member+publish-only == publisher).

I may just have to not implement publish-only until this is resolved.

**Comment by stpeter** [comment]
The publish-only affiliation was intended for mere information sources, if you will. But I'm not sure I fully understand your question. And in any case the standards@xmpp.org discussion list is the best place for questions like this. :-) 

http://mail.jabber.org/mailman/listinfo/standards

**Comment by linuxwolf** [comment]
Future discussion on this issue to happen on standards@xmpp.org.
