### ISSUE TITLE
ProtoXEP: OpenPGP for XMPP (OX)

### ISSUE THREAD

**Issue by ashward** [xsf/xeps#167]
IPR Response from Authors:
- [x] Florian
- [x] Vincent
- [x] Dominik

**Comment by ashward** [comment]
Response from Dominik

> In accordance with the XSF IPR policy, do you:
> 
> 1. Acknowledge you own the rights to the content in the submitted proposal?
> 
> yes
> 
> 
> 2. Assign those rights to the XMPP Standards Foundation upon acceptance
> of the proposal?
> 
> yes
> 
> Cheers
> Dominik Schürmann

**Comment by ashward** [comment]
Added to council agenda: https://trello.com/c/RBZ4vNFf/101-protoxep-openpgp-for-xmpp-accept-as-experimental

**Comment by ashward** [comment]
Response form Florian

> In accordance with the XSF IPR policy, do you:
> 
> 1. Acknowledge you own the rights to the content in the submitted proposal?
> 
> Yes
> 
> 2. Assign those rights to the XMPP Standards Foundation upon acceptance
> of the proposal?
> 
> Yes
> 
> - Florian
>

**Comment by Flowdalic** [comment]
Correct me if I'm wrong, but I believe all council members have voted positive about OX and OX-IM, so there is nothing left preventing the publication as experimental XEPs.
