### ISSUE TITLE
README should contain usage directions

### ISSUE THREAD

**Issue by SamWhited** [xsf/xeps#18]
The README should really contain directions for generating HTML from one of the XEP XML files. It's unclear to me what the current process for that is.

**Comment by dwd** [comment]
I think the correct process is to use the XSF website... :-)

A problem with specifying how to render your own XEPs is that people may think these are the current XEPs - whereas they may not be.

**Comment by SamWhited** [comment]
This would be for people writing XEPs (eg. before they've been submitted).

**Comment by linuxwolf** [comment]
I think providing some guidance to XEP writers on how to create the rendered HTML is worth adding.

**Comment by stpeter** [comment]
I'll update the README and provide a pointer to XEP-0143.

**Comment by bear** [comment]
I am going to take a pass at creating a tools README
