### ISSUE TITLE
 XEP-0358: Registrar considerations

### ISSUE THREAD

**Issue by SamWhited** [xsf/xeps#190]
This PR: https://github.com/xsf/xeps/pull/189/files adds registrar considerations, but I don't think we have an actual registry right now, or a repo for the registry, or anyone who knows how to handle the registry. Leaving this issue as a reminder to add the contents of that PR to the registry in the future when we get it back.

Please correct me if I'm wrong about any of this; I might just not know where the registry stuff lives or how to deal with it. /cc @stpeter @ashward

**Comment by Kev** [comment]
I've created a new registrar.git, owned by the Editors, with the content of the registrar directory in the old repo. If you let us know how to get this served in the appropriate way, we'll get on it.

**Comment by SamWhited** [comment]
Awesome, thanks @kev! I just realized that this issue actually didn't make sense because we only add things to the registry when they go to draft (I think?), so I'll close this issue for now. We'll have somewhere to put it in future though.
