### ISSUE TITLE
XEP-0060: publish-options element missing from schema

### ISSUE THREAD

**Issue by horazont** [xsf/xeps#191]
[Section 7.1.5 of XEP-0060](https://xmpp.org/extensions/xep-0060.html#publisher-publish-options) refers to `<publish-options/>`. It is not defined in any of the schemas in XEP-0060.

I also brought this issue up [on the standards mailing list](http://mail.jabber.org/pipermail/standards/2016-May/031125.html) (link leads to my email in the mailing list archive).

**Comment by stpeter** [comment]
See https://github.com/xsf/xeps/pull/328 and https://github.com/xsf/schemas/pull/3
