### ISSUE TITLE
Make XEP publishing more automatic

### ISSUE THREAD

**Issue by SamWhited** [xsf/xeps#211]
I see three options here:
- Setup a deploy stage in Travis after all checks are green
- Setup a cron job on perseus to pull once an hour or so and publish any changes
- Setup a webhook in GitHub that hits an endpoint on perseus when there are new changes on master (and then have perseus run whatever scripts are necessary)

**Comment by Kev** [comment]
> I see three options here:
> 
> Setup a deploy stage in Travis after all checks are green
> Setup a cron job on perseus to pull once an hour or so and publish any changes
> Setup a webhook in GitHub that hits an endpoint on perseus when there are new changes on master (and then have perseus run whatever scripts are necessary)
Of these, I feel most comfortable with (1). I’d rather not have the concern of running endpoints on perseus for (3) that we’d have to care about not being hugely vulnerable. If we could render with Travis, push the result to a git repo and then cronjob on perseus to deploy, that seems good to me.

/K

**Comment by guusdk** [comment]
changes to https://github.com/xsf/xeps/ as well as to https://github.com/xsf/xep-attic/ now cause an automatic build of a new Docker image on [Docker Hub](https://hub.docker.com/r/xmppxsf/). Eos has been configured to check for an updated docker image every five minutes.

Is any more automation desired?

**Comment by SamWhited** [comment]
I think we'll still want some sort of automation around the attic, but we can file a new issue for that. Thanks for all your hard work on this Guus!

**Comment by stpeter** [comment]
👍  and thanks to Guus!
