### ISSUE TITLE
Several merged but unpublished XEPs

### ISSUE THREAD

**Issue by linkmauve** [xsf/xeps#256]
This revision [Editors note: XEP-0144] seems to have been stalled since the 2012-06-19, according to the date element of the latest revision, and has never been published on xmpp.org.

This has been found thanks to xsf-tools’ xeputils chocking while parsing the date.

**Comment by SamWhited** [comment]
[ ] https://github.com/xsf/xeps/pull/184

**Comment by Kev** [comment]
Merged but unpublished doesn't always mean that it should be published now. The old way of working on the repo was to push stuff to trunk as a working branch, and publish when ready. Care is needed.

**Comment by SamWhited** [comment]
Good to know; thanks!

**Comment by Flowdalic** [comment]
The latest versions of XEP-0300, -0037, -0230 have been published.
