### ISSUE TITLE
Change the "Deferred" Text

### ISSUE THREAD

**Issue by Flowdalic** [xsf/xeps#27]
Was decided in Council's 2013-07-24 meeting:
- http://logs.xmpp.org/council/2013-07-24/#15:12:14
- http://mail.jabber.org/pipermail/council/2013-August/003748.html
- http://mail.jabber.org/pipermail/council/2013-July/003737.html

should become

> WARNING: This document has been automatically *Deferred* after 12
> months of inactivity in its previous *Experimental* state.
> Implementation of the protocol described herein is not recommended
> for production systems. However, exploratory implementations are
> encouraged to resume the standards process.

**Comment by ralphm** [comment]
YAY!
