### ISSUE TITLE
XEP-0143: Maintaining an XEP section needs review

### ISSUE THREAD

**Issue by SamWhited** [xsf/xeps#281]
https://xmpp.org/extensions/xep-0143.html#maintain still says that the editor prefers to receive patches via email. Should we now add that it's possible to submit a GitHub pull request?

**Comment by Kev** [comment]
More than being possible, I think the Editors preference is now to receive PRs, although email remains open as an option?
So I think yes.

**Comment by stpeter** [comment]
See https://github.com/xsf/xeps/pull/306

**Comment by SamWhited** [comment]
Fixed by 475fa51
