### ISSUE TITLE
Audit / remove old HTML

### ISSUE THREAD

**Issue by SamWhited** [xsf/xeps#295]
There are several (S)HTML files scattered about the repo that can most likely be removed. The ones that provide redirects can be handled in the xsf/xmpp.org repo instead, or in the nginx config; either way they probably shouldn't be in the xeps repo.

**Comment by stpeter** [comment]
I see:

all.shtml
editor.shtml
index.shtml
ipr-policy.shtml
submit.shtml

I think all of these can be deleted.

And yes, we might need to put redirects in place in nginx.

**Comment by intosi** [comment]
I suspect you'll find that there are redirects in nginx for these already.

**Comment by SamWhited** [comment]
I'll open an issue against xsf/xmpp.org for creating redirects and ask the iteam to make sure they don't need the shtml files for some reason.

**Comment by intosi** [comment]
@SamWhited really, no need:

rewrite ^/extensions/all.shtml      http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite ^/extensions/editor.shtml   http://xmpp.org/about-xmpp/xsf/xsf-people/#extensions;
rewrite ^/extensions/index.php      http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite ^/extensions/index.shtml    http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite ^/extensions/ipr-policy.shtml   http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/;

They have been there for quite a while.  I don't see any reason for keeping them.

**Comment by stpeter** [comment]
Nuke 'em!

(Are we still allowed to say that?)

**Comment by intosi** [comment]
@stpeter: not since '45, I think.

**Comment by SamWhited** [comment]
Thanks all! I'll remove these "soon"
