### ISSUE TITLE
Change terminology in XEP-0053

### ISSUE THREAD

**Issue by stpeter** [xsf/xeps#298]
In line with IANA terminology, I would prefer to change "Proposed" and "Standard" for registry entries to "Provisional" and "Permanent". See for instance http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml as governed by https://tools.ietf.org/html/rfc7595. I will submit a PR for this.

**Comment by stpeter** [comment]
See https://github.com/xsf/xeps/pull/303

**Comment by SamWhited** [comment]
Fixed.
