### ISSUE TITLE
XEP-0045 maxhistoryfetch doesn't have the roomconfig_ prefix

### ISSUE THREAD

**Issue by jcbrand** [xsf/xeps#310]
While studying MUC-0045, I noticed that the maxhistoryfetch configuration field doesn't have the `roomconfig_` prefix which the other fields have.

See for example here: http://xmpp.org/extensions/xep-0045.html#example-157

Is this due to legacy or actually a bug?

**Comment by stpeter** [comment]
In the early days of MUC we prefixed all the config options with `roomconfig_` but then we figured out that it wasn't necessary and in fact was somewhat silly (because the form is already namespaced), so we stopped the practice. I don't think this is a bug.

**Comment by jcbrand** [comment]
Thanks for the explanation.

My 2 cents. I would have preferred just sticking to the convention, even if it was determined to not have been strictly necessary to begin with, it has been established. Now there is an inconsistency which can be confusing.
