### ISSUE TITLE
XEP-0384: Misleading naming of KEY/IV tags

### ISSUE THREAD

**Issue by andreygursky** [xsf/xeps#322]
Considering "4.5 Sending a message": there is a KEY/IV pair and a KEY/IV elements, which could be easily confused. Moreover the KEY element consists of encrypted data, but IV not. What do you think about changing the naming of the KEY element to something more explicit like "ENCRYPTED_KEY"?

**Comment by Flowdalic** [comment]
I suggest bringing this topic to the [standards@](https://mail.jabber.org/mailman/listinfo/standards) mailing lists. Github issues are not the primary place for protocol discussions.

**Comment by andreygursky** [comment]
Thanks for your suggestion. I'll bring also my consecutive issues to the list.

**Comment by andreygursky** [comment]
Follow-up: https://mail.jabber.org/pipermail/standards/2016-December/031724.html

**Comment by SamWhited** [comment]
Going to close this; it's not entirely clear right now where this issue should be filed, but since there's list discussion I don't think we need to track it here.
