### ISSUE TITLE
XEP-0384 and inbox/omemo-filetransfer: Variable length of MAC

### ISSUE THREAD

**Issue by andreygursky** [xsf/xeps#324]
> The 16 bytes key and the GCM authentication tag (The tag SHOULD have at least 128 bit) are concatenated and for each intended recipient device...

Once received due to the predefined length of the first field (key), the length of the tag can be calculated. Considering OMEMO file-transfer: the tag is appended at the end of the encrypted file and the total length is reported to the receiver. It seems to me not possible to derive the used authentication tag length in this case.

**Comment by andreygursky** [comment]
Follow-up: https://mail.jabber.org/pipermail/standards/2016-December/031726.html

**Comment by SamWhited** [comment]
OMEMO file transfer has been withdrawn by the author.
