### ISSUE TITLE
XEP-0384: Missing definition of key signing protocol

### ISSUE THREAD

**Issue by andreygursky** [xsf/xeps#326]
Now that OMEMO moved from Axolotl to Olm, the explicit definition of how keys must be signed and verified should be added into the XEP.

**Comment by andreygursky** [comment]
Follow-up: https://mail.jabber.org/pipermail/standards/2016-December/031736.html

**Comment by SamWhited** [comment]
Going to close this; it's not entirely clear right now where this issue should be filed, but since there's list discussion I don't think we need to track it here.
