### ISSUE TITLE
XEP-0300 should define the encoding format

### ISSUE THREAD

**Issue by tfar** [xsf/xeps#349]
We should check that XEPs using XEP-0300 use the right encoding in the examples.

XEP-0300 examples currently use a **Base64 encoding**, but does not explicitly specify it in the text. However, it seems the XEPs using XEP-0300, use a different encoding format:

Considering, most of them don't use the exact XEP-0300 hash element but custom attributes and elements.

- XEP-0234 uses **hex encoding**
- XEP-0264 uses **hex encoding** as it is based on the XEP-0234 application format
- XEP-0329 uses **hex encoding** as it is based on the XEP-0234 application format
- XEP-0343 uses **hex encoding** as it is based on the XEP-0234 application format
- XEP-0370 uses **hex encoding** as it is based on the XEP-0234 application format
- XEP-0385 uses **hex encoding** as it is based on the XEP-0234 application format

**Comment by tfar** [comment]
Probably it's most sensible to adjust XEP-0300 to use hex encoding as current Jingle File-Transfer implementations all use hex encoding anyway I think.

**Comment by Zash** [comment]
Should probably investigate if there are any implementations anywhere and what they do.

**Comment by tfar** [comment]
> Probably it's most sensible to adjust XEP-0300 to use hex encoding as current Jingle File-Transfer implementations all use hex encoding anyway I think.

My assumption was wrong. At least Swift uses Base64 encoding.

https://github.com/swift/swift/blob/master/Swiften/Parser/PayloadParsers/JingleFileTransferFileInfoParser.cpp#L70

**Comment by Zash** [comment]
Seems Gajim does hex?

https://dev.gajim.org/gajim/python-nbxmpp/blob/master/nbxmpp/protocol.py#L1327

**Comment by tfar** [comment]
Seems the sensible things here is to increase XEP-0300 version number and explicitly define the encoding format. Don't know if XEPs using XEP-0300 also have to change their version number.

**Comment by dwd** [comment]
Agreed. If there are multiple encodings, let's add that into the spec as you say. It is possible to guess heuristically which encoding has been used, mind.

**Comment by tfar** [comment]
Are you suggesting adding support for multiple encodings to the spec?

**Comment by tfar** [comment]
My suggestion would be to update XEP-0300 to `urn:xmpp:hashes:2` and mandate Base64 encoding, as it's more efficient than hex encoding, and also used by some RFCs, e.g. RFC 6920 and RFC 7517, and also some XEPs like XEP-0115.

**Comment by tfar** [comment]
Update: XEP-0300 has been updated.

**Comment by SamWhited** [comment]
Fixed by 2f21fbef22d484d1651596aeb279b3386398c183
