### ISSUE TITLE
index file for references directory

### ISSUE THREAD

**Issue by stpeter** [xsf/xeps#351]
In the past, we had an index file at https://xmpp.org/extensions/refs/ so that one could look at the list of reference files. This was used by some automated services (such as https://xml2rfc.tools.ietf.org/ - scroll down). Perhaps we can create a cron job to auto-generate an index.html or index.txt file. (This might be more of an iteam issue...)

**Comment by SamWhited** [comment]
I think this is more of a website issue; I have a similar isssue open at xsf/xmpp.org#224

**Comment by stpeter** [comment]
Yep, I will close this issue.
