### ISSUE TITLE
Defer experimental XEPs that have not been updated in 12 months

### ISSUE THREAD

**Issue by SamWhited** [xsf/xeps#369]
I suppose at some point we had XEPs automatically being deferred after 12 months of inactivity, but I was glancing through some XEPs and discovered quite a few that should be deferred but aren't.

It would be good to do a survey of existing experimental XEPs and defer the ones that haven't been touched in a while.

**Comment by winfried** [comment]
On 17-01-17 07:32, Sam Whited wrote:
> It would be good to do a survey of existing experimental XEPs and defer
> the ones that haven't been touched in a while.

Not very hard... hmmm, guess XEP-370 should not be in this list.

winfried@missie:~/Data/werk/XSF/xsf-tools$ ./testscript.py -x ../xeps/
creating /tmp/XEPs_PBWrcX for output
Interim:
[XEP-0001, XEP-0030, XEP-0144, XEP-0266]
No short name:
[]
Last Call:
[XEP-0186, XEP-0280, XEP-0296, XEP-0332, XEP-0352]
Expired:
XEP-0215 2015-10-20 00:00:00
XEP-0233 2015-10-20 00:00:00
XEP-0264 2015-08-26 00:00:00
XEP-0286 2015-07-24 00:00:00
XEP-0292 2013-09-12 00:00:00
XEP-0298 2015-07-02 00:00:00
XEP-0318 2013-08-06 00:00:00
XEP-0320 2015-10-15 00:00:00
XEP-0323 2015-11-09 00:00:00
XEP-0324 2015-11-09 00:00:00
XEP-0325 2015-11-09 00:00:00
XEP-0326 2015-11-09 00:00:00
XEP-0330 2013-06-11 00:00:00
XEP-0331 2015-11-09 00:00:00
XEP-0333 2015-10-28 00:00:00
XEP-0334 2015-09-01 00:00:00
XEP-0335 2013-10-25 00:00:00
XEP-0336 2015-11-09 00:00:00
XEP-0337 2015-11-09 00:00:00
XEP-0338 2014-01-08 00:00:00
XEP-0339 2015-11-09 00:00:00
XEP-0340 2014-01-08 00:00:00
XEP-0341 2014-01-14 00:00:00
XEP-0342 2014-03-13 00:00:00
XEP-0343 2014-07-15 00:00:00
XEP-0344 2015-03-23 00:00:00
XEP-0345 2014-08-04 00:00:00
XEP-0346 2014-04-10 00:00:00
XEP-0348 2015-11-09 00:00:00
XEP-0349 2014-06-18 00:00:00
XEP-0350 2014-07-03 00:00:00
XEP-0351 2014-08-28 00:00:00
XEP-0353 2014-10-02 00:00:00
XEP-0354 2014-10-15 00:00:00
XEP-0356 2015-03-23 00:00:00
XEP-0360 2015-07-14 00:00:00
XEP-0361 2015-07-18 00:00:00
XEP-0362 2015-08-11 00:00:00
XEP-0365 2015-09-17 00:00:00
XEP-0367 2015-12-15 00:00:00
XEP-0368 2015-12-15 00:00:00
XEP-0370 2016-01-12 00:00:00
********** Error report for XEP-0144 **********
********** Parsing Errors **********
Invalid value for date while parsing XEP-0144, setting to a default.
  XEP file: /home/winfried/Data/werk/XSF/xeps/xep-0144.xml
  Error: time data 'in progress, last updated 2012-06-19' does not match
format '%Y-%m-%d'

**Comment by SamWhited** [comment]
@winfried wow, thanks! That's a longer list than I thought. I'll try to find some time after work to go through and validate / mark those as deprecated. Thanks again!
