### ISSUE TITLE
XEP-0313: Add "queryid" attribute to "fin" element

### ISSUE THREAD

**Issue by olesalscheider** [xsf/xeps#379]
The "query" and "result" elements of XEP-0313 have a "queryid" attribute that can be used to associate the results to the query. The "fin" element in the final IQ however does not have this attribute.

Is it just missing in the XEP or is this deliberate? How can I associate the final IQ to the query otherwise?

**Comment by SamWhited** [comment]
@olesalscheider Hi there, this is an issue tracker for the XEPs repo. For discussion I recommend the [standards@xmpp.org](https://mail.jabber.org/mailman/listinfo/standards) mailing list or the [xsf@muc.xmpp.org](xmpp:xsf@muc.xmpp.org?join) chat room.

**Comment by Flowdalic** [comment]
Sam is right. But the short answer is: It's deliberate and you can associate the final IQ like you can associate every result/error IQ to its request IQ counterpart: By the stanza ID and the from/to tuple.
