### ISSUE TITLE
MIX: misuse of a subject element

### ISSUE THREAD

**Issue by zinid** [xsf/xeps#380]
Section 5.1.15 (Setting the Channel Subject) from XEP-0369 is incorrect, because RFC6121 forbids using mixed content in `<subject/>` elements (section 5.2.4, at the bottom). Instead, it should be rewritten as:
```xml
<message from='hag66@shakespeare.example/pda'
         to='coven@mix.shakespeare.example'
         id='92vax143g'
         type='groupchat'>
  <subject xml:lang="en">How to use Toads</subject>
  <subject xml:lang="de">Wie benutzt man Kröten</subject>
</message>
```

**Comment by Flowdalic** [comment]
You are right. Pinging @stevekille

**Comment by stevekille** [comment]
Thanks!   Will fix this.

**Comment by stevekille** [comment]
This change is made, and will be in the next MIX update

 

S
