### ISSUE TITLE
Makefile cannot build html/pdf from xml files in inbox.

### ISSUE THREAD

**Issue by vanitasvitae** [xsf/xeps#507]
I might as well do something wrong, but afaict it is currently not possible to build html or pdf files from the inbox folder.
```
$ make ./inbox/xxx.html
make: *** Keine Regel, um „inbox/xxx.html“ zu erstellen.  Schluss.
```

**Comment by SamWhited** [comment]
The output directory is "build" by default. `make build/inbox/xxx.html`

**Comment by vanitasvitae** [comment]
Ah great, thanks :)
