### ISSUE TITLE
Update XEP copyright

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xeps#589]
Please update the XEP copyright: 2017 to 2018 and regenerate PDF files.

Thanks in advance.

**Comment by SamWhited** [comment]
At least in ths U.S. this isn't how copyright notification works and it is not necessary to update this. In fact, you probably *don't* want to update it; the copyright statement establishes how far back the claim on a work goes, so it should be the date of first publication.

**Comment by Neustradamus** [comment]
I think that do not understand.
Look the top of https://xmpp.org/extensions/xep-0001.html :)
-> 2017 and the version has from 2016.

It was updated year after year, there is an oversight this year!

**Comment by SamWhited** [comment]
When we update the XEPs it gets updated, but it probably shouldn't be. It doesn't really matter either way though, the copyright statement doesn't mean much.

**Comment by Neustradamus** [comment]
But it was updated previously, I have already made one or more requests in the past on the JIRA...

**Comment by SamWhited** [comment]
It probably shouldn't have been updated previously, since this isn't supposed to be how copyright statements work.

**Comment by Neustradamus** [comment]
This has been validated, it does not happen alone.

Every year, the year changes normally...

**Comment by SamWhited** [comment]
As I said, it shouldn't have, so let's not continue the pattern of bad behavior.

**Comment by Neustradamus** [comment]
No problem, I will wait a little time ^^

For research: https://github.com/xsf/xeps/commit/48d668e5f0ea09d59573f253a6cff739d6dc3a30#diff-4b1ec939a0860928054dc60b4cbd41f2

**Comment by SamWhited** [comment]
Yes, that was a mistake. I have since learned that you're not supposed to do this.

**Comment by Flowdalic** [comment]
> so it should be the date of first publication.

Shoudn't it be the year when the version was first published? For example if I do a version bump of a XEP in 2018, which was first published in 2016, then the copyright should state 2016-2018?

**Comment by SamWhited** [comment]
Yes; the range isn't really useful either, so it should probably just read "Copyright <year of first publication>" and leave it at that. It doesn't really matter though, so I don't think there's any change that needs to be made. Just let it update when new revisions are pushed or whatever it does right now.

**Comment by Flowdalic** [comment]
I thought this was about updating the copyright in LEGALNOTICE in `xep.ent`, but @horazont already did take care of that: https://github.com/xsf/xeps/commit/d4387fe5ccbbbc7c13ef6e049e4e64db3182895b

Everything is fine.
