### ISSUE TITLE
Council Actions 2018-03-07

### ISSUE THREAD

**Issue by dwd** [xsf/xeps#601]
- [x] Deprecate XEP-0020
- [x] Issue CFE XEP-0048
- [x] Issue CFE XEP-0066
- [x] Issue CFE XEP-0092
- [x] Issue CFE XEP-0122
- [x] Issue CFE XEP-0131
- [x] Issue CFE XEP-0141
- [x] Issue CFE XEP-0229
- [x] Apply #600, once Georg has changed feature string
- [x] Apply #593

**Comment by horazont** [comment]
I’m gonna emit the CFEs in weekly batches of two. This is to take load off the developers. If you disagree, please let me know here or in the usual places.

(Alternatively, we could extend the feedback period, but I think that weekly batches will work better. Helps with not letting things fall off the developers agenda, and also takes load off council to process the feedback.)

**Comment by dwd** [comment]
My understanding of XEP-0001 suggests that Council can simply ask the Editors for a CFE (like anyone else), and there's no time limit as regards when the Editor does so, so I agree this is acceptable.

On a personal note, I'm glad you're doing this because otherwise there'll be 7 Advance-To-Final votes in Council on the same week...
