### ISSUE TITLE
XEP-0305 does not address mutual authentication

### ISSUE THREAD

**Issue by xnyhps** [xsf/xeps#69]
SCRAM-SHA-1 allows mutual authentication: not just the server establishes that the client knows the password, but also the other way around. This works because the server includes a specifically crafted hash on the `<success/>` element.

XEP-0305 seems to suggest that the client should ignore this:

> When the client suspects that it is sending its final SASL response, with pipelining it appends an initial stream header and resource binding request.

In my opinion, XEP-0305 should either:

* Note explicitly that the client still MUST process the final SASL message from the server, and if the response indicates an authentication failure, immediately close the connection. The client MUST NOT pipeline anything beyond the bind `<iq>` (assuming that the resource is not considered sensitive).
* Forbid pipelining until the client has sent and _received_ all SASL messages. This adds one more roundtrip, but it ensures nothing is leaked.

**Comment by stpeter** [comment]
Before making changes to this spec, I would like to determine if anyone is still interested in implementing it.

**Comment by stpeter** [comment]
I've initiated a list discussion here: 

http://mail.jabber.org/pipermail/standards/2015-September/030347.html

**Comment by SamWhited** [comment]
Closing since XEP-0305 is deferred. Feel free to re-open discussion on the mailing list if necessary.
