### ISSUE TITLE
Bookmarks-Conversion should not have a favorite

### ISSUE THREAD

**Issue by guusdk** [xsf/xeps#712]
The wording in https://xmpp.org/extensions/inbox/bookmarks-conversion.html implies a preference of PEP over Private XML Storage. Although that's reasonable in many situation, such a preference definition does not add any value to the XEP (and might only confuse people, or refrain people from Private XML Storage when there might be good reason to use it.

Maybe the wording should be changed in a way that does only describe how both interact, without implying preference?

**Comment by SamWhited** [comment]
I tend to disagree with this, but it might be worth bringing up on list if you want the most people to see it.

**Comment by horazont** [comment]
Please don’t have technical discussion in the issue tracker. Move it to standards@, so that all interested parties only need to follow a single place.

(And I think this is technical.)
