### ISSUE TITLE
XEP-0283: Moved - allow automatic transfer

### ISSUE THREAD

**Issue by ge0rg** [xsf/xeps#717]
The lack of an automatic mechanism to transfer my roster from account A to account B is a major impediment in moving to a better maintained server.

[https://xmpp.org/extensions/xep-0283.html](XEP-0283: Moved) contains the protocol to make such an automatic transition possible, minus server side caching of the `moved` element in the unsubscribe stanza. However, the XEP strictly warns against automatic change of the sender JID on the receiving side.

I think that the fear documented in the XEP is not appropriate. An entity that proves ownership of both accounts (by publishing corresponding moved elements on both) should be allowed to perform such a roster change. On domains where roster is controlled by administrative restrictions on the server, such a change shouldn't be technically possible anyway.

I would like to loosen the requirements in the XEP (by means of a PR) , if the general idea is accepted by the Council.

**Comment by SamWhited** [comment]
This should be brought up on the mailing list so that council will actually see it.

**Comment by ge0rg** [comment]
Let me jump into my time-machine and give Council half a year to provide feedback...

https://mail.jabber.org/pipermail/standards/2018-March/034553.html

There it is, even with comments from Council members, albeit not answering the actual question. Do you suggest I resurrect that thread and explicitly ask for a vote / opinions on the question itself there, or can we get the "Needs Council" badge on this one? :)

**Comment by horazont** [comment]
Let me reiterate. Issues (and PRs) are not for technical discussion. The Needs Council tag is for a concrete PR where Council needs to make a decision. This is not even a PR. Please stop cluttering the xeps repository.

This repository is for *editors*. Please don’t use it for council organisation. It clutters my editor inbox and worsens the signal/noise ratio, impeding efficient working.
