### ISSUE TITLE
XEP-0394: Support for hyperlinks

### ISSUE THREAD

**Issue by cmrd-senya** [xsf/xeps#722]
As XHTML-IM was deprecated there seem to be no way to explicitly make a hyperlink. Since XEP-0394 is a proposed replacement for XHTML-IM, I propose to add support for hyperlink markup there. Inline markup seems a valid category for it.

**Comment by SeveFP** [comment]
Hey @cmrd-senya 
This topic should go in the standards mailing list https://mail.jabber.org/pipermail/standards/
We don't use GitHub for protocol discussions.
