### ISSUE TITLE
XEP-README should be updated to reflect new GitHub-based workflow

### ISSUE THREAD

**Issue by winfried** [xsf/xeps#73]
According to the current status, experimental, it should be deferred by now...

**Comment by stpeter** [comment]
Well it's not a real XEP. :-) It was originally just for internal documentation so that I didn't forget how to do certain things. Now that we have a team, perhaps it deserves to have a different status but I don't know that it ever really needs to be a XEP.

**Comment by linuxwolf** [comment]
I'm not sure I'd want this to be a real XEP.  Unless the XEP Editor team can be an "approving body", I'd rather not be hamstrung by meta-processes.

Also, it needs serious updating.

**Comment by SamWhited** [comment]
I've been updating this as I figure out how to do the various tasks. Closing this for now.

**Comment by Mikaela** [comment]
Does this issue also affect https://github.com/xsf/xeps/blob/master/.github/ISSUE_TEMPLATE.md ?

>  You are using an old version of issue templates. Please update to the new issue template workflow. Learn more
