### ISSUE TITLE
Problem with publication dates

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xeps#966]
There is a problem in several XEPs.

It is needed to solve it.

Date of publication of the XEP and change dates.

Example:
- https://xmpp.org/extensions/xep-0390.html

```
Appendix H: Revision History

Note: Older versions of this specification might be available at http://xmpp.org/extensions/attic/

Version 0.3.2 (2018-03-05)
Explain that ASCII Seperators are only invalid in XML 1.0, but not in XML 1.1.
fs

Version 0.3.1 (2020-04-28)
Add another xml:lang example
fs

Version 0.3.0 (2018-10-01)
Defer due to lack of activity.
XEP Editor (jsc)
```

**Comment by Ppjet6** [comment]
It has been explained to you that this is not an issue. The author kindly included a revision block with dates but changes haven't been merged in the same order (because things happen).

Who cares anyway? Closing.

**Comment by horazont** [comment]
Let me explain this in more detail.

### How revision dates are chosen

Revision dates are the dates you see on a XEP revision history. There are two different ways the dates can be selected:

1. A change is proposed for a XEP. The author of the change picks a date and puts it in the change.
2. A change is proposed for a XEP. The author of the change *does not* pick a date. The editors add a date when the change is processed.

When the first case happens, there can be a (long) delay between the date the author chose and the date at which the change is published.

If the first case and the second case happen with two different changes and they are processed in different orders, it can happen that the dates are not ascending.

This is to simplify the editor process. We could also re-write the date in revision blocks from authors. But that is error prone, so we generally do not do that. It also generally is not a problem.

### Revision dates are not publication dates

It is as simple as that.

### How to fix?

Not at all. We cannot fix revisions which are already out there. They are archived; the emails have been sent; nothing can be fixed here. It is a problem for certain tools if the most recent revision does not reflect the most recent change and we should avoid this in the future.

**Comment by Neustradamus** [comment]
Timeline:
- https://i.ibb.co/H40xXmR/Timeline-example.png

For XEP-0390:
- https://i.ibb.co/12TcWX0/Timeline-XEP-0390.png

A commit (or several commits) can be done but the official publication date must be the date of the publication/release/announcement.

If the XSF publishes a XEP the 2020-01-01, it is must in the XEP:

```
Version X.X.X.X (2020-01-01)
Description
Publisher
```
